name: whats_app_thom
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  get: 4.1.4
  flutter: 
    sdk: flutter
  get_cli: ^1.5.0
  flutter_svg: ^0.22.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset : fonts/OpenSans-Bold.ttf
        - asset : fonts/OpenSans-Regular.ttf
        - asset : fonts/OpenSans-Italic.ttf
          style: italic

